server:
  port: 8011
  servlet:
    context-path: /

spring:
    profiles:
    active: dev

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    appname: guanaitong-client
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://peer1:9000/eureka/,http://peer2:9000/eureka/,http://peer3:9000/eureka/

GAT_APP_ID: appId which got from guan ai tong
GAT_APP_SECRET: appSceret which got from guan ai tong


